name: cypher
description: A new Flutter plugin to generate passwords which can contain digits, lower case letters, upper case letters and punctuations.
version: 1.0.0
homepage: https://deepnote.app

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  plugin:
    platforms:
      android:
        package: com.example.cypher
        pluginClass: CypherPlugin
      ios:
        pluginClass: CypherPlugin
