name: cypher
description: Generates passwords which can contain digits, lower case letters, upper case letters and punctuations.
version: 2.0.1
homepage: https://github.com/sinan-aktepe/cypher

environment:
  sdk: ^3.5.0
  flutter: '>=3.24.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
